<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <TestOperatingSystem>Windows</TestOperatingSystem>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Agash.StreamTransport.Windows\Agash.StreamTransport.Windows.csproj" />
    <ProjectReference Include="..\..\src\Agash.StreamTransport\Agash.StreamTransport.csproj" />
    <ProjectReference Include="..\..\src\Agash.StreamTransport.Codecs.FFmpeg\Agash.StreamTransport.Codecs.FFmpeg.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <Compile
      Include="..\Agash.StreamTransport.Tests\LoopbackSignaling.cs"
      Link="LoopbackSignaling.cs"
    />
  </ItemGroup>
</Project>
